##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Make PiP float
windowrule {
	name = float-PiP
	match:title = Picture-in-Picture
	float = yes
}

windowrule {
	name = wiremix
	match:class = wiremix
	float = yes
}

windowrule {
	name = steam-friends
	match:class = steam
	match:title = Friends List
	float = yes
}

windowrule {
	name = steam-community-server
	match:class = steam
	match:title = Game Servers
	float = yes
}

# Make pavucontrol float at top right
# windowrulev2 = float, class:org.pulseaudio.pavucontrol
# windowrulev2 = size 30% 50%, class:org.pulseaudio.pavucontrol
# windowrulev2 = move 100%-w-0 3%, class:org.pulseaudio.pavucontrol
